### ISSUE TITLE
Map animation

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#102] opened 2017-08-28 20:14 UTC
Trying to play an animation in the map for the Salinity NWGOFS and NGOFS.  As the animation runs the layer's data image keeps disappearing. 

The CO-OPS NWGOFS animation runs hourly, so it's unclear why the EDS animation isn't finding hourly data. https://tidesandcurrents.noaa.gov/ofs/ofs_animation.shtml?ofsregion=ng&subdomain=ma&model_type=salinity_nowcast

**Comment by kknee** [comment] 2018-04-10 12:25
@kbailey-noaa we did a bunch of testing and couldn't reproduce the issue.  I have seen what you describe before, but usually when we are having trouble acquiring a source, so its not really an issue with the animation itself.  I think we can close this one.

**Closed** 2018-04-12 18:11 UTC
Labels: ForReview, Jira
